version: 2.1
orbs:
  slack: circleci/slack@4.10.1

# Define the jobs we want to run for this project
jobs:
  Sonrai_Demosix_Production:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run: mkdir sanity;
      - run: jmeter -n -t Demosix_Prod_AllFlows_GraphqlOperations_Final.jmx -l sanity/Demosix_Prod_Demo_steps_test.jtl -e -o sanity/Demosix_Prod_Demo -j sanity/jmeter.log
      - run: ls -l
      - run: |
             if [ $(grep false sanity/Demosix_Prod_Demo_steps_test.jtl | wc -l) -eq "0" ]; then
               echo "pass"
               exit 0
             else 
               echo "fail"
               exit 1
             fi
      
      - store_artifacts:
         path: sanity
      - slack/notify:
         channel: performance-production
         event: fail
         mentions: 'To view Demosix production Result - Click on View Job,go to Artificats folder and select index.html file'
         template: basic_fail_1
      - slack/notify:
          channel: performance-production
          event: pass
          mentions: 'To view Demosix production Result - Click on View Job,go to Artificats folder and select index.html file'
          template: basic_success_1

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - Sonrai_Demosix_Production:
          context: slack-secrets
