version: 2.1

# Define the jobs we want to run for this project
jobs:
  Sonrai_Demosix_Production:
    docker:
      - image: justb4/jmeter:latest
    steps:
      - checkout
      - run: mkdir sanity;
      - run: jmeter -n -t Demosix_Prod_Demo_steps.jmx -l sanity/Demosix_Prod_Demo_steps_test.jtl -e -o sanity/Demosix_Prod_Demo -j sanity/jmeter.log
      - run: ls -l
      - run: grep false sanity/Demosix_Prod_Demo_steps_test.jtl | wc -l
      # run: jmeter -n -t Staging_Appinsight_summery_full.jmx -l /sanity/Staging_Summary_Test2.jtl -e -o /sanity/StagingSummary_Test2
      # run: jmeter -n -t Sonrai_PCAPIAPIs.jmx -l /sanity/PCAPI_TestResult.jtl -e -o /sanity/PCAPI_1
      # run: jmeter -n -t Sonrai_Graphql_staging.jmx -l /tmp/artifacts/runResults4.jtl -e -o /sanity/result2
      - store_artifacts:
         path: sanity

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - Sonrai_Demosix_Production
